apiVersion: v1
kind: Pod
metadata:
  name: slow
spec:
  containers:
    - name: slow
      image: registry.cn-guangzhou.aliyuncs.com/yleoer/slow:1.0.1
      imagePullPolicy: IfNotPresent
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
      env:
        - name: START_TIME
          value: 2m
      startupProbe:
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 30
        tcpSocket:
          port: 8080
      livenessProbe:
        initialDelaySeconds: 1
        timeoutSeconds: 2
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 2
        httpGet:
          port: 8080
          path: /healthy
      readinessProbe:
        initialDelaySeconds: 1
        timeoutSeconds: 2
        periodSeconds: 3
        successThreshold: 1
        failureThreshold: 2
        httpGet:
          port: 8080
          path: /ready
  restartPolicy: Always
  