apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow
  labels:
    app: slow
spec:
  replicas: 3
  selector:
    matchLabels:
      app: slow
  template:
    metadata:
      labels:
        app: slow
    spec:
      containers:
        - name: slow
          image: registry.cn-guangzhou.aliyuncs.com/yleoer/slow:1.1.0
          env:
            - name: START_TIME
              value: 10s
          startupProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /ready
