apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: mem-example
spec:
  containers:
    - name: memory-demo-ctr
      image: registry.cn-guangzhou.aliyuncs.com/yleoer/stress:latest
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: 100Mi
        limits:
          memory: 200Mi
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]