apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-2
  namespace: mem-example
spec:
  restartPolicy: Never
  containers:
    - name: memory-demo-2-ctr
      image: registry.cn-guangzhou.aliyuncs.com/yleoer/stress:latest
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: 50Mi
        limits:
          memory: 100Mi
      command: ["stress"]
      args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]